stages:
  - build
  - stage
  - deploy

build:
  stage: build
  image: ruby:2.6
  cache:
    paths:
      - vendor
  artifacts:
    paths:
      - public
  tags:
    - apps
    - docker
  script:
    # Print out ruby version for debugging
    - ruby -v
    - gem install bundler
    # Install dependencies into ./vendor/ruby
    - bundle install -j $(nproc) --path vendor/ruby
    - bundle exec jekyll build -d public

stage:
  stage: stage
  environment:
    name: me.randen.bp
    url: http://me.randen.bp
  tags:
    - apps
    - shell
  only:
    - master
  script:
    - rsync -aPv ./public/ /srv/randen/

deploy:
  stage: deploy
  image: python:3.8
  environment:
    name: randen.me
    url: http://randen.me
  tags:
    - apps
    - docker
  when: manual
  only:
    - master
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install awscli
    - aws s3 sync ./public s3://randen.me/
